### ISSUE TITLE
release as a standalone desktop program

### ISSUE THREAD

**Issue by ghost** [1x6/xenylist#15]
do you have any plans to release this as a regular executable? without the server stuff

**Comment by lasersPew** [comment]
> do you have any plans to release this as a regular executable? without the server stuff

This is a server app LOL. Don't ask for it to become a desktop app, work on it yourself and don't make a PR of it here as everything in here are server stuff. The developer won't do the feature afaik.

**Comment by 1x6** [comment]
i don't have any plans to do that as laserspew said but you could probably do it by combining the server and a web browser instance.
